/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#6fd8c8',
        'surface-container-low': '#f2f4f6',
        'background': '#f8f9fb',
        'primary': '#00458f',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#005cbb',
        'tertiary-container': '#4d616c',
        'surface-dim': '#d8dadc',
        'outline-variant': '#c2c6d4',
        'tertiary': '#354954',
        'on-primary-fixed': '#001b3f',
        'on-secondary-fixed': '#00201c',
        'surface-container': '#eceef0',
        'primary-fixed-dim': '#abc7ff',
        'secondary': '#006b5f',
        'on-surface': '#191c1e',
        'surface': '#f8f9fb',
        'on-tertiary': '#ffffff',
        'outline': '#727784',
        'inverse-surface': '#2d3133',
        'surface-variant': '#e1e3e5',
        'on-tertiary-fixed': '#081e27',
        'primary-fixed': '#d7e2ff',
        'surface-container-high': '#e6e8ea',
        'on-primary-container': '#c7d9ff',
        'on-surface-variant': '#424752',
        'on-tertiary-fixed-variant': '#364954',
        'on-primary-fixed-variant': '#00458f',
        'tertiary-fixed-dim': '#b4cad6',
        'inverse-on-surface': '#eff1f3',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#c6dbe8',
        'error': '#ba1a1a',
        'secondary-fixed': '#8cf5e4',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e1e3e5',
        'on-background': '#191c1e',
        'inverse-primary': '#abc7ff',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'on-secondary-container': '#007166',
        'surface-tint': '#005cbb',
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#005048',
        'secondary-container': '#8cf5e4',
        'surface-bright': '#f8f9fb',
        'tertiary-fixed': '#d0e6f3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Public Sans', 'sans-serif'],
        headline: ['Public Sans', 'sans-serif'],
        body: ['Public Sans', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 12px 32px -4px rgba(25, 28, 30, 0.06)',
        'card': '0 4px 16px -2px rgba(25, 28, 30, 0.08)',
      },
    },
  },
  plugins: [],
}
